version: '3'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
